### ISSUE TITLE
[BUG]Wrong meanRowWise calculation in Matrix module

### ISSUE THREAD

**Issue by koba140** [fslaborg/FSharp.Stats#119]
**Describe the bug**
Row sum needs to be divided by number of columns instead of rows

**To Reproduce**

```
let mat = matrix
                    [
                        [20.;  11.];
                        [6.;  29.];
                        [12.;  8.];
                    ]
Matrix.meanRowWise mat
```

**Expected behavior**
`Vector [15.5; 17.5; 10]`

**Actual Behavior**
`Vector [10.33333333; 11.66666667; 6.666666667]`

**Comment by ZimmerD** [comment]
Thank you for your feedback! I had a look and the correct behavior should now be in place.

**Comment by koba140** [comment]
Thank you. I am Working on the unit tests already.
