### ISSUE TITLE
Example Goodnes of FIt Notebook fails to load nuget packages due to Microsoft.DotNet.Interactive dependency

### ISSUE THREAD

**Issue by YnnamTenob** [fslaborg/FSharp.Stats#127]
**Describe the bug**
Cannot load nuget packages in binder due to MIcrosoft.DotNet.Interactive.
**To Reproduce**
1. Navigate to [FSharp.Stats/GoodnessOfFit](https://fslab.org/FSharp.Stats/GoodnessOfFit.html)
2. Click Launch Binder top of page
3. Run first cell to install nuget packages

```
#r "nuget: Plotly.NET, 2.0.0-beta3"
#r "nuget: Plotly.NET.Interactive, 2.0.0-alpha5"
#r "nuget: FSharp.Stats"
```

Installing package Plotly.NET, version 2.0.0-beta3..................
Installing package FSharp.Stats..................
Installing package Plotly.NET.Interactive, version 2.0.0-alpha5..................
/tmp/nuget/40--9cd08fa5-7b2c-46c4-a437-4db6636fb86d/Project.fsproj : error NU1102: Unable to find package Microsoft.DotNet.Interactive with version (= 1.0.0-beta.20574.9)
/tmp/nuget/40--9cd08fa5-7b2c-46c4-a437-4db6636fb86d/Project.fsproj : error NU1102:   - Found 14 version(s) in nuget.org [ Nearest version: 1.0.0-beta.21108.3 ]
/tmp/nuget/40--9cd08fa5-7b2c-46c4-a437-4db6636fb86d/Project.fsproj : error NU1102: Unable to find package Microsoft.DotNet.Interactive.Formatting with version (= 1.0.0-beta.20574.9)
/tmp/nuget/40--9cd08fa5-7b2c-46c4-a437-4db6636fb86d/Project.fsproj : error NU1102:   - Found 14 version(s) in nuget.org [ Nearest version: 1.0.0-beta.21108.3 ]
/tmp/nuget/40--9cd08fa5-7b2c-46c4-a437-4db6636fb86d/Project.fsproj : error NU1102: Unable to find package Microsoft.DotNet.Interactive.FSharp with version (= 1.0.0-beta.20574.9)
/tmp/nuget/40--9cd08fa5-7b2c-46c4-a437-4db6636fb86d/Project.fsproj : error NU1102:   - Found 14 version(s) in nuget.org [ Nearest version: 1.0.0-beta.21108.3 ]

**Expected behavior**
No errors in loading packages

**Comment by bvenn** [comment]
Thanks for the report.
I've updated the Plotly.NET versions. This should fix the issue. Consider reopening, if something else fails.

**Comment by kMutagene** [comment]
@YnnamTenob related issue on Plotly.NET: https://github.com/plotly/Plotly.NET/issues/67

in short, we can not do much against .NET Interactive using non-Nuget.org packages, but you can migitate this problem with all versions by including their package sources:

```
#i "nuget:https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json"
#i "nuget:https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json"
```

**Comment by YnnamTenob** [comment]
Plotly 2.0.0 beta 8 fixed the binder issues I experienced.
