### ISSUE TITLE
 Revise hierarchical clustering documentation

### ISSUE THREAD

**Issue by bvenn** [fslaborg/FSharp.Stats#131]
While a hierarchical clustering example is provided in the documentation, proper description of linking methods are missing. To understand the input/output types of hierarchical clustering you have to dive deeply into the topic. An illustrated guide should be provided, that introduces into the different types of linkers and explains the values of the cluster in detail.
Furthermore `HierarchicalClustering.generate` could be renamed into `cluster` thereby introducing an additional `clusterBy` function. A Plotly.NET visualization of the final tree would be nice to have as well.

 - [x] revise documentation (introduce linking methods)
 - [x] revise documentation (describe tree output)
 - [x] (optional) visualization

**Comment by kMutagene** [comment]
Regarding visualization: I am not aware of a way to visualize networks with plotly.NET. However, there is [Cyjs.NET](https://github.com/fslaborg/Cyjs.NET) which seems to be perfectly fit for that task. I looked into it at least a bit, and there are [taxi edges](https://js.cytoscape.org/demos/edge-types/) (left lower corner of the edge examples) for these types of tree plots (which will also be helpful for visualizing phylogenetic trees, but thats another issue).

**Comment by bvenn** [comment]
I'm going to link my [clustering blogposts](https://fslab.org/content/tutorials/003_clustering_hierarchical.html) at fslab in the documentation and adapt the current documentation to it. 
Regarding the visualization, @HLWeil gave some hints in his [blogpost](https://fslab.org/content/tutorials/007_replicate-quality-control.html#Data-visualization):+1:, thus i'm going to integrate this as well.

**Comment by bvenn** [comment]
@zieglerSe, have you made progress in the hclust performance improvement?

**Comment by bvenn** [comment]
closed by #267
