### ISSUE TITLE
[BUG] List.median does not return the same thing as Seq.median and Array.median

### ISSUE THREAD

**Issue by nhirschey** [fslaborg/FSharp.Stats#184]
**Describe the bug**
List.median returns a tuple of two numbers whose average is the median, whereas `Seq.median` and `Array.median` return the medians. Should these all produce the same result? 

**To Reproduce**

```fsharp
#r "nuget: FSharp.Stats,0.4.3"

open FSharp.Stats

[|1.0; 2.0 |] |> Array.median // 1.5
seq [ 1.0; 2.0] |> Seq.median // 1.5
[ 1.0; 2.0] |> List.median // (1.0, 2.0)
```

**Expected behavior**
I expect the same result for these collections.

**OS and framework information (please complete the following information):**
 - OS: Windows 11 
 - .Net core SDK version 6.0.200

**Additional context**

**Comment by bvenn** [comment]
You're right, the output should be as the output of the median function in the Seq and Array module. While checking the function, I encountered another problem. If nans are inside the sequence, I think a median function should also output `nan` as a result. This is the case for `Seq.median` and `Array.median`, but not for `List.median`. I'll have a look at it

**Comment by bvenn** [comment]
I think that for `infinity` and `-infinity` a valid result should be possible, only nan must be a special case.

**Comment by bvenn** [comment]
`List.median` now results in the median itself. Additionally I updated `List.median` to work with types other than `float`. I added unit tests for:
```
List.median
List.mean
Seq.median
Seq.mean
Array.median
```
each covering `nan`, `infinity` and `-infinity` cases.

**Comment by nhirschey** [comment]
Thank you! This fix looks fantastic.
