### ISSUE TITLE
Quantiles.OfSorted.* XML comments incorrectly say the functions work with unsorted arrays.

### ISSUE THREAD

**Issue by nhirschey** [fslaborg/FSharp.Stats#186]
Two observations, if you are happy with my suggestions then I will submit PRs with a fix. I think (1) is important but if you don't like (2) below I won't be upset.

1. The XML comments for functions in `Quantile.OfSorted` are incorrect. They say that the functions work with unsorted arrays, but they actually require sorted arrays. I propose that the XML comment is changed to say they require **sorted** arrays. [Example](https://github.com/fslaborg/FSharp.Stats/blob/8f9f5bab3043e6f358a799e207fc4acee5067031/src/FSharp.Stats/Quantile.fs#L142)
2. The functions directly inside `Quantile` such as [Quantile.compute](https://github.com/fslaborg/FSharp.Stats/blob/8f9f5bab3043e6f358a799e207fc4acee5067031/src/FSharp.Stats/Quantile.fs#L254) create a copy of the input and sort that copy. These thus seem to be designed as low friction interfaces. What about allowing sequences as input, so that users could pass in sequences or lists with slightly less friction?

**Comment by bvenn** [comment]
Both suggestions sound good to me. Because in the end all functions apply `Array.quickSelectInPlace` an array conversion is necessary but keeping the input generic should be the way to go. Thanks @nhirschey!
