### ISSUE TITLE
[BUG] Link error in the doc

### ISSUE THREAD

**Issue by thomasd3** [fslaborg/FSharp.Stats#187]
On the first page of the doc (basics) there is a link to the HarmonicMean on Wikipedia, but that link goes to the edit page.

It is:
    https://en.wikipedia.org/w/index.php?title=Harmonic_mean&action=edit&section=1

and should be:
    https://en.wikipedia.org/w/index.php?title=Harmonic_mean

**Comment by bvenn** [comment]
The change will be available after the next docs release :+1:
