### ISSUE TITLE
[Feature Request] Move distance metrics from the ML module to Linear Algebra

### ISSUE THREAD

**Issue by Recktenwald** [fslaborg/FSharp.Stats#200]
**Is your feature request related to a problem? Please describe.**
Since F# enforces strict linearity, the distance metrics are only usable in the ML module and the ones after it in the .fsproj file. In particular, they are not usable in the optimization module, I am currently working on.

**Describe the solution you'd like**
Put the distance in the linear algebra module. For code that already uses the distance metrics, this would break backward compatibility. I.e. someone calling `ML.DistanceMetrics.euclidean` would find their code no longer working

**Comment by muehlhaus** [comment]
I think we should move "DistanceMetrics" into the Core module. This makes it usable everywhere and would be a better place anyway. We can reference it in the ML module and deprecate it there... This should fix the problems

**Comment by bvenn** [comment]
I would also prefer moving DistanceMetrics into core, right beneath Correlation. @Recktenwald, shall I make the changes or do you want to do it along with the optimization PR?

**Comment by Recktenwald** [comment]
You can go ahead and just make the change right now, I think it will take some time until I will do the PR.

**Comment by bvenn** [comment]
closed by 4f4e08b440c7122f3ac39fd4cd014796560369cd
