### ISSUE TITLE
[Feature Request] Quadratic Mean

### ISSUE THREAD

**Issue by axrwl** [fslaborg/FSharp.Stats#233]
Quadratic mean or RMS is a very popular measure which seems to be missing.
[Wikipedia page for Quadratic mean](https://en.wikipedia.org/wiki/Root_mean_square)

**Comment by bvenn** [comment]
Thanks for your contribution, the commit looks fine 🚀 Could you add some unit tests for the new functions? You could copy the [mean tests](https://github.com/fslaborg/FSharp.Stats/blob/3bf8e23177ad93bf19f0ed5293f83d78539dd602/tests/FSharp.Stats.Tests/Seq.fs#L44) to check the meanQuadratic for validity.
