### ISSUE TITLE
[Feature Request] Vector.linspace

### ISSUE THREAD

**Issue by kMutagene** [fslaborg/FSharp.Stats#235]
**Is your feature request related to a problem? Please describe.**
numpy.linspace (https://numpy.org/doc/stable/reference/generated/numpy.linspace.html) - a function creating a evenly spaced vector in a specified range - is used in every python tutorial/blogpost ever. Adding this simple function would reduce boilerplate code needed to translate such samples

**Describe the solution you'd like**
a function `Vector.linspace`

**Describe alternatives you've considered**
meh

**Comment by bvenn** [comment]
WIP
