### ISSUE TITLE
[BUG] SAM permutation problem with unbalanced data

### ISSUE THREAD

**Issue by zieglerSe** [fslaborg/FSharp.Stats#243]
Using unbalanced data in SAM leads to wrong results. Change in indices during permutation required.

**Comment by ZimmerD** [comment]
I think the faulty behavior can be caused by line 246:

`(id,x.[..replicateCount1-1]),(id,x.[replicateCount2..])`

Changing it to:

`(id,x.[..replicateCount1-1]),(id,x.[replicateCount1..])`

could fix the observed output
