### ISSUE TITLE
Minkowski distance

### ISSUE THREAD

**Issue by bvenn** [fslaborg/FSharp.Stats#296]
### Description

>The Minkowski distance or Minkowski metric is a metric in a normed vector space which can be considered as a generalization of both the Euclidean distance and the Manhattan distance. [1]

### References

- [1] https://en.wikipedia.org/wiki/Minkowski_distance

### Pointers

- the implementation should be located here: https://github.com/fslaborg/FSharp.Stats/blob/developer/src/FSharp.Stats/DistanceMetrics.fs
- within FSharp.Stats.DistanceMetrics, there are specialized modules `Vector` and `Array`, that contain the same functionality as the overarching module, but are optimized for high performance. You should first implement a version, that works on two sequences of generic type and if appropriate add optimized versions within `DistanceMetrics.Vector` and `DistanceMetrics.Array`.
- if not inferred automatically, you can ensure that the function works on any input collection (float, int), by adding the inline keyword
  ```fsharp
  let inline minkowski (s1: seq<'a>) (s1: seq<'a>) (p: int) : float =
      //iterate over both collections and determine the Minkowski distance
      //using a single fold function may be sufficient
  ```
- optional: add unit tests for sequences of int, float according to [this](https://github.com/fslaborg/FSharp.Stats/blob/8fb5d6dd07ff213a4e91b618fb2e654bc6147985/tests/FSharp.Stats.Tests/DistanceMetrics.fs#L10) example.
  - don't forget to test negative values within the input sequence, as well as 0. and nan entries
- optional: add proper XML documentation #281
- Of course you can start developing in notebooks/scripts and afterwards we try to incorporate into the library.

<details>

<summary>Hints (click to expand if you need additional pointers)</summary>

- To be able to contribute to this library you'll need 
  - an GitHub account
  - an IDE like Visual Studio Community or Visual Studio Code
  - [dotnet 6 sdk](https://dotnet.microsoft.com/en-us/download)
- to build the binaries yourself follow the [instructions](https://fslab.org/FSharp.Stats/#Installation)
- while working on the [FSharp.Stats documentation](https://fslab.org/FSharp.Stats/) (any file within https://github.com/fslaborg/FSharp.Stats/tree/developer/docs) you can navigate to the project folder with a prompt of your choice and use the command `./build watchdocs`
- unit tests can be executed via `./build runtests` 

</details>

**Comment by s-weil** [comment]
I will work on this issue

**Comment by s-weil** [comment]
Hi @bvenn 

I would like to open my PR on this issue, but haven't been able to publish my branch yet.
Are there any write restrictions in place?
Thanks a lot for the help

**Comment by bvenn** [comment]
Hi @s-weil 

first of all: Thank you for your contribution 👍 

You have to fork the repo and open a PR from the feature-branch of your fork to the developer branch of fslaborg. I hope that helps. If not, dont hesitate in contacting again.

**Comment by s-weil** [comment]
Thanks, that helped. the PR is here: https://github.com/fslaborg/FSharp.Stats/pull/308
