### ISSUE TITLE
kNN classification

### ISSUE THREAD

**Issue by bvenn** [fslaborg/FSharp.Stats#300]
### Description

> KNN which stand for K Nearest Neighbor is a Supervised Machine Learning algorithm that classifies a new data point into the target class, depending on the features of its neighboring data points.
[1]

### References

- [1] https://www.edureka.co/blog/knn-algorithm-in-r/#:~:text=KNN%20Algorithm%20Pseudocode%3A&text=Initialize%20k%20and%20take%20the,put%20x%20in%20class%20i.
- [2] https://www.analyticsvidhya.com/blog/2021/04/simple-understanding-and-implementation-of-knn-algorithm/

### Pointers
- A new Classification folder can be added to the FSharp.Stats.ML namespace. There you can create a KNN.fs source file and add the implementation according to its analogs in R or python. 
- Of course you can start developing in notebooks/scripts and afterwards we try to incorporate into the library.

**Comment by s-weil** [comment]
I'd be happy to work on this issue.
