### ISSUE TITLE
[BUG] HierarchicalClustering cannot digest data of generic type anymore

### ISSUE THREAD

**Issue by kMutagene** [fslaborg/FSharp.Stats#321]
See 

https://github.com/fslaborg/FSharp.Stats/blob/3533493bda96ee8277f0bad793e11187617e3bf9/src/FSharp.Stats/ML/Unsupervised/HierarchicalClustering.fs#L483-L490

while `generate<'T>` uses a generic, the `data` argument is hard coded to `array<float[]>`, which was not the case in older versions.

**Comment by kMutagene** [comment]
Hey @bvenn can we release a 0.6.0 that contains this change or are there other boxes to tick for such a release? this blocks updating BioFSharp as it will not build with the non-generic clustering. let me know how i can help

**Comment by bvenn** [comment]
Hi, yes, Im going to release 0.6.0 :rocket:

**Comment by bvenn** [comment]
https://github.com/fslaborg/FSharp.Stats/releases/tag/0.6.0
