### ISSUE TITLE
Switch order of parameters in modules 'Matrix' and 'Vector'

### ISSUE THREAD

**Issue by bvenn** [fslaborg/FSharp.Stats#43]
### Description

For piping convenience the matix/vector input should be the last parameter in functions from modules 'Matrix' and 'Vector'

Example:

```
Matrix.getCols (m: Matrix<float>) (i: int) 
Vector.get (v: Vector) (i: int)
```
should be 

```
Matrix.getCols (i: int) (m: Matrix<float>)
Vector.get (i: int) (v: Vector)
```

- [ ] add unit tests for Vector module
- [ ] add unit tests for Matrix module

- Before clean up and pushing implement unit tests
- Compare parameter order with Core functions
- If functions are renamed or parameter order is switched, keep the old naming with `[<Obsolete("Do not use. Use [function name] instead.")>]` Tag
- parameter renaming can be performed without further attention

**Comment by Freymaurer** [comment]
I looked into the vector module and changed the following

- change input parameter position some functions as requested by @bvenn 
- Adjust parameter names to FSharp.Core naming
- clean up docs
- clean up function names (remove underscored)

PR coming in a few minutes.
