### ISSUE TITLE
[Feature Request] H-test (Kruskal-Wallis one-way ANOVA)

### ISSUE THREAD

**Issue by zieglerSe** [fslaborg/FSharp.Stats#81]
Kruskal-Wallis one-way ANOVA is good for comparing means of independent samples that are non-parametric.

**Comment by bvenn** [comment]
implemented in #82

- [x] implementation
- [x] documentation
- [ ] unit tests

**Comment by bvenn** [comment]
unit test added by 62554534f0f748320995211e9bf51315b3ff89ed
